# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('about', models.CharField(max_length=500)),
                ('banner', models.CharField(max_length=254)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
