# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20161008_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
