# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20161008_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='last_modified',
            field=models.DateField(),
        ),
    ]
